version: 2.1

jobs:
  hello-job:
    docker:
      - image: cimg/base:current # the primary container, where your job's commands are run
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" # run the `echo` command
      - run: echo "yeett"
      - run: sleep 3000

workflows:
  my-workflow:
    jobs:
      - hello-job
